
# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin
# This is a generated file produced by scripts/pr-ci-matrix.rb.

xcode_version: 
 - 11.3
 - 11.4.1
 - 11.7
 - 12.0
 - 12.1
target: 
 - cocoapods-catalyst
configuration: 
 - Debug
 - Release

exclude:

  - xcode_version: 11.3
    target: cocoapods-catalyst
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-catalyst
    configuration: Debug

  - xcode_version: 11.4.1
    target: cocoapods-catalyst
    configuration: Release

  - xcode_version: 11.7
    target: cocoapods-catalyst
    configuration: Debug

  - xcode_version: 11.7
    target: cocoapods-catalyst
    configuration: Release

  - xcode_version: 12.0
    target: cocoapods-catalyst
    configuration: Debug

  - xcode_version: 12.0
    target: cocoapods-catalyst
    configuration: Release

  - xcode_version: 12.1
    target: cocoapods-catalyst
    configuration: Debug
